<?php

use App\Services\SQSClientService;
use Aws\Sqs\SqsClient;

class SQSClientResolverTest extends TestCase
{
    public $resolver;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->resolver = $this->app->make(SQSClientService::class);
    }

    /** @test */
    public function it_returns_sqs_client_resolver_on_instantiate()
    {
        $this->assertInstanceOf(SQSClientService::class, $this->resolver);
    }

    /** @test */
    public function it_returns_an_instance_of_sqs_client()
    {
        $client = $this->resolver->client();

        $this->assertInstanceOf(SqsClient::class, $client);
    }
}