<?php

use App\Resolvers\SQSClientResolver;
use Aws\Sqs\SqsClient;

class SQSClientResolverTest extends TestCase
{
    public $resolver;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->resolver = $this->app->make(SQSClientResolver::class);
    }

    /** @test */
    public function it_returns_sqs_client_resolver_on_instantiate()
    {
        $this->assertInstanceOf(SQSClientResolver::class, $this->resolver);
    }

    /** @test */
    public function it_returns_an_instance_of_sqs_client()
    {
        $client = $this->resolver->client();

        $this->assertInstanceOf(SqsClient::class, $client);
    }
}