<?php

use App\Action;
use App\Events\InboundMessagesWasSynced;
use App\InboundMessage;
use App\Listeners\ProcessSyncedInboundMessages;
use App\Repositories\Eloquent\InboundMessageRepositoryEloquent;
use App\Repositories\Eloquent\InboundMessageLogRepositoryEloquent;
use App\Subscriber;

class ProcessSyncedInboundMessagesTest extends BaseTestCase
{
    use AWSTestHelpers;

    /**
     * @var InboundMessageRepositoryEloquent
     */
    private $message;

    /**
     * @var ProcessSyncedInboundMessages
     */
    private $listener;

    /**
     * @var InboundMessageLogRepositoryEloquent
     */
    private $messageLog;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->listener = $this->app->make(ProcessSyncedInboundMessages::class);
        $this->message = $this->app->make(InboundMessageRepositoryEloquent::class);
        $this->messageLog = $this->app->make(InboundMessageLogRepositoryEloquent::class);
    }

    /** @test */
    public function locateTest()
    {
        $this->runningTestFor(get_class($this));
    }

    /** @test */
    public function it_sets_status_sent_on_successful_message_sent_to_subscriber()
    {
        $eventInstance = $this->prepareInstanceOfSqsMessageWasSynced(['url' => url($this->SUCCESS_RESPONSE_SITE())]);

        $messages = $this->message->findAllWhereIn('message_id', $eventInstance->messageIdList, ['action']);
        $subscriberAttachInput = collect([]);
        foreach ($messages as $message) {
            foreach ($message->action->subscriber as $subscriber) {
                $subscriberAttachInput->put($subscriber->id, ['status' => 'sent']);
            }
        }

        $this->listener->handle($eventInstance);

        $this->assertMultipleSeeInDatabase('inbound_sent_message', $subscriberAttachInput->toArray());
    }

    /** @test */
    public function it_sets_status_failed_to_unsuccessful_message_sent_to_subscriber()
    {
        $eventInstance = $this->prepareInstanceOfSqsMessageWasSynced(['url' => url($this->UNSUCCESSFUL_RESPONSE_SITE())]);

        $messages = $this->message->findAllWhereIn('message_id', $eventInstance->messageIdList, ['action']);
        $subscriberAttachInput = collect([]);
        foreach ($messages as $message) {
            foreach ($message->action->subscriber as $subscriber) {
                $subscriberAttachInput->put($subscriber->id, ['status' => 'failed']);
            }
        }

        $this->listener->handle($eventInstance);

        $this->assertMultipleSeeInDatabase('inbound_sent_message', $subscriberAttachInput->toArray());
    }

    //to test unserialized input

    /** @test */
    public function it_sets_status_failed_when_subscriber_url_is_invalid()
    {
        $eventInstance = $this->prepareInstanceOfSqsMessageWasSynced(['url' => url('http://mueller.org/quas-vel-non-nisi-quia-tenetur-aut-culpa')]);
        $subscriberAttachInput = $this->buildToAssertIfEqualMessageInput($eventInstance->messageIdList, 'failed');

        $this->listener->handle($eventInstance);

        $this->assertMultipleSeeInDatabase('inbound_sent_message', $subscriberAttachInput->toArray());
    }

    /** @test */
    public function it_does_not_add_to_attach_if_there_is_no_associated_subscriber_on_message_action()
    {
        $firstAction = factory(Action::class)->create(['name' => 'changed']);
        $secondAction = factory(Action::class)->create(['name' => 'changed']);
        $messagesOnFirstAction = factory(InboundMessage::class, 5)->create([
            'action_id' => $firstAction->id,
            'message_content' => $this->SAMPLE_SALESFORCE_TO_SQS_MESSAGE()
        ]);
        $messagesOnSecondAction = factory(InboundMessage::class, 5)->create([
            'action_id' => $secondAction->id,
            'message_content' => $this->SAMPLE_SALESFORCE_TO_SQS_MESSAGE()
        ]);
        $subscriberOne = factory(Subscriber::class, 3)->create(['url' => url($this->SUCCESS_RESPONSE_SITE())]);

        $firstAction->subscriber()->attach(collect($subscriberOne)->pluck('id')->toArray());

        $firstMessageIdList = $this->collectMessageIdsOnActions($messagesOnFirstAction);
        $secondMessageIdList = $this->collectMessageIdsOnActions($messagesOnSecondAction);

        $messageIdList = array_merge($firstMessageIdList, $secondMessageIdList);
        $sqsMessageWasSynced = new InboundMessagesWasSynced($messageIdList);

        $subscriberAttachInput = $this->buildToAssertIfEqualMessageInput($sqsMessageWasSynced->messageIdList);

        $this->listener->handle($sqsMessageWasSynced);

        $savedMessages = InboundMessage::with('subscriber')->get();

        $total = 0;
        foreach ($savedMessages as $message) {
            $total += $message->subscriber->count();
        }

        $this->assertMultipleSeeInDatabase('inbound_sent_message', $subscriberAttachInput->toArray());
        $this->notSeeInDatabase('inbound_sent_message', ['status' => 'failed']);
        $this->assertEquals(15, $total);
    }

    public function it_receives_to_be_decoded_form_input()
    {
        $action = factory(Action::class)->create(['name' => 'changed']);
        $message = factory(InboundMessage::class)->create([
            'action_id' => $action->id,
            'message_content' => $this->SAMPLE_SALESFORCE_TO_SQS_MESSAGE()
        ]);

        $subscriber = factory(Subscriber::class)->create(['url' => url($this->FORMS_PARAMS_RESPONSE_SITE())]);

        $action->subscriber()->attach($subscriber->id);

        $sqsMessageWasSynced = new InboundMessagesWasSynced([$message->message_id]);
        $this->listener->handle($sqsMessageWasSynced);
    }

    /** @test */
    public function it_insert_to_message_logs()
    {
        $eventInstance = $this->prepareInstanceOfSqsMessageWasSynced(['url' => url($this->SUCCESS_RESPONSE_SITE())]);

        $messages = $this->message->findAllWhereIn('message_id', $eventInstance->messageIdList, ['action']);
        $subscriberAttachInput = collect([]);
        foreach ($messages as $message) {
            foreach ($message->action->subscriber as $subscriber) {
                $subscriberAttachInput->put($subscriber->id, ['status' => 'sent']);
            }
        }

        $this->listener->handle($eventInstance);

        $this->assertEquals(25, $this->messageLog->all()->count());
    }

    /**
     * @param array $subscriberCreateOptions
     * @return InboundMessagesWasSynced
     */
    private function prepareInstanceOfSqsMessageWasSynced($subscriberCreateOptions = [])
    {
        $firstAction = factory(Action::class)->create(['name' => 'changed']);
        $secondAction = factory(Action::class)->create(['name' => 'changed']);

        $messagesOnFirstAction = factory(InboundMessage::class, 5)->create([
            'action_id' => $firstAction->id,
            'message_content' => $this->SAMPLE_SALESFORCE_TO_SQS_MESSAGE()
        ]);
        $messagesOnSecondAction = factory(InboundMessage::class, 5)->create([
            'action_id' => $secondAction->id,
            'message_content' => $this->SAMPLE_SALESFORCE_TO_SQS_MESSAGE()
        ]);

        $subscriberOne = factory(Subscriber::class, 3)->create($subscriberCreateOptions);
        $subscriberTwo = factory(Subscriber::class, 2)->create($subscriberCreateOptions);

        $firstAction->subscriber()->attach(collect($subscriberOne)->pluck('id')->toArray());
        $secondAction->subscriber()->attach(collect($subscriberTwo)->pluck('id')->toArray());

        $firstMessageIdList = $this->collectMessageIdsOnActions($messagesOnFirstAction);
        $secondMessageIdList = $this->collectMessageIdsOnActions($messagesOnSecondAction);

        $messageIdList = array_merge($firstMessageIdList, $secondMessageIdList);

        return new InboundMessagesWasSynced($messageIdList);
    }

    /**
     * @param array $messages
     * @return array
     */
    private function collectMessageIdsOnActions($messages)
    {
        $messageIdList = [];

        foreach ($messages as $message) {
            $messageIdList[] = $message->message_id;
        }

        return $messageIdList;
    }

    /**
     * @param array $messageIdList
     * @param string $status
     * @return \Illuminate\Support\Collection
     */
    private function buildToAssertIfEqualMessageInput($messageIdList, $status = 'sent')
    {
        $messages = $this->message->findAllWhereIn('message_id', $messageIdList, ['action']);
        $subscriberAttachInput = collect([]);
        foreach ($messages as $message) {
            foreach ($message->action->subscriber as $subscriber) {
                $subscriberAttachInput->put($subscriber->id, ['status' => $status]);
            }
        }

        return $subscriberAttachInput;
    }

}
